const commonPersonItems = [
  { label: '证件种类', code: 'IDType' },
  { label: '证件号码', code: 'IDNumber' },
  { label: '姓名', code: 'Name' },
  { label: '曾用名', code: 'UsedName' },
  { label: '绰号', code: 'Alias' },
  { label: '性别', code: 'GenderCode' },
  { label: '年龄上限', code: 'AgeUpLimit' },
  { label: '年龄下限', code: 'AgeLowerLimit' },
  { label: '民族', code: 'EthicCode' },
  { label: '国籍', code: 'NationalityCode' },
  { label: '籍贯省市县', code: 'NativeCityCode' },
  { label: '居住地行政区划', code: 'ResidenceAdminDivision' },
  { label: '汉语口音', code: 'ChineseAccentCode' },
  { label: '职业类别', code: 'JobCategory' },
  { label: '同行人脸数', code: 'AccompanyNumber' },
  { label: '肤色', code: 'SkinColor' },
  { label: '发型', code: 'HairStyle' },
  { label: '发色', code: 'HairColor' },
  { label: '脸型', code: 'FaceStyle' },
  { label: '脸部特征', code: 'FacialFeature' },
  { label: '体貌特征', code: 'PhysicalFeature' },
  { label: '口罩颜色', code: 'RespiratorColor' },
  { label: '帽子款式', code: 'CapStyle' },
  { label: '帽子颜色', code: 'CapColor' },
  { label: '眼镜款式', code: 'GlassStyle' },
  { label: '眼镜颜色', code: 'GlassColor' },
  { label: '是否驾驶员', code: 'IsDriver' },
  { label: '是否涉外人员', code: 'IsForeigner' },
  { label: '护照证件种类', code: 'PassportType' },
  { label: '出入境人员类别', code: 'ImmigrantTypeCode' },
  { label: '是否涉恐人员', code: 'IsSuspectedTerrorist' },
  { label: '涉恐人员编号', code: 'SuspectedTerroristNumber' },
  { label: '是否涉案人员', code: 'IsCriminalInvolved' },
  { label: '涉案人员专长代码', code: 'CriminalInvolvedSpecilisationCode' },
  { label: '体表特殊标记', code: 'BodySpeciallMark' },
  { label: '作案手段', code: 'CrimeMethod' },
  { label: '作案特点代码', code: 'CrimeCharacterCode' },
  { label: '在逃人员编号', code: 'EscapedCriminalNumber' },
  { label: '是否在押人员', code: 'IsDetainees' },
  { label: '看守所编码', code: 'DetentionHouseCode' },
  { label: '在押人员身份', code: 'DetaineesIdentity' },
  { label: '在押人员特殊身份', code: 'DetaineesSpecialIdentity' },
  { label: '成员类型', code: 'MemberTypeCode' },
  { label: '是否被害人', code: 'IsVictim' },
  { label: '被害人种类', code: 'VictimType' },
  { label: '受伤害程度', code: 'InjuredDegree' },
  { label: '尸体状况', code: 'CorpseConditionCode' },
  { label: '是否可疑人', code: 'IsSuspiciousPerson' },
  { label: '姿态分布', code: 'Attitude' },
  { label: '相似度', code: 'Similaritydegree' },
  { label: '眉型', code: 'EyebrowStyle' },
  { label: '鼻型', code: 'NoseStyle' },
  { label: '胡型', code: 'MustacheStyle' },
  { label: '嘴唇', code: 'LipStyle' },
  { label: '皱纹眼袋', code: 'WrinklePouch' },
  { label: '痤疮色斑', code: 'AcneStain' },
  { label: '黑痣胎记', code: 'FreckleBirthmark' },
  { label: '疤痕酒窝', code: 'ScarDimple' },
  { label: '其他特征', code: 'OtherFeature' },
]
export const ColumnItems: any = {
  // 人脸
  'Face': [
    { label: '人脸标识', code: 'FaceID' },
    { label: '信息分类', code: 'InfoKind' },
    { label: '来源标识', code: 'SourceID' },
    { label: '关联卡口编号', code: 'TollgateID' },
    { label: '左上角X坐标', code: 'LeftTopX' },
    { label: '左上角Y坐标', code: 'LeftTopY' },
    { label: '右上角X坐标', code: 'RightBtmX' },
    { label: '右上角Y坐标', code: 'RightBtmy' },
    { label: '位置标记时间', code: 'MarkTime', type: 'time' },
    { label: '人脸出现时间', code: 'FaceAppearTime', type: 'time' },
    { label: '人脸消失时间', code: 'FaceDisAppearTime ', type: 'time' },
    ...commonPersonItems
  ],
  // 人员
  'Person': [
    { label: '人员标识', code: 'PersonID' },
    { label: '信息分类', code: 'InfoKind' },
    { label: '来源标识', code: 'SourceID' },
    { label: '左上角X坐标', code: 'LeftTopX' },
    { label: '左上角Y坐标', code: 'LeftTopY' },
    { label: '右上角X坐标', code: 'RightBtmX' },
    { label: '右上角Y坐标', code: 'RightBtmy' },
    { label: '位置标记时间', code: 'LocationMarkTime', type: 'time' },
    { label: '人员出现时间', code: 'PersonAppearTime', type: 'time' },
    { label: '人员消失时间', code: 'PersonDisAppearTime', type: 'time' },
    ...commonPersonItems
  ],
  // 机动车
  'MotorVehicle': [
    { label: '车辆标识', code: 'MotorVehicleID' },
    { label: '信息分类', code: 'InfoKind' },
    { label: '来源标识', code: 'SourceID' },
    { label: '关联卡口编号', code: 'TollgateID' },
    { label: '近景照片', code: 'StorageUrl1', type: 'image' },
    { label: '车牌照片', code: 'StorageUrl2', type: 'image' },
    { label: '远景照片', code: 'StorageUrl3', type: 'image' },
    { label: '合成图', code: 'StorageUrl4', type: 'image' },
    { label: '缩略图', code: 'StorageUrl5', type: 'image' },
    { label: '左上角X坐标', code: 'LeftTopX' },
    { label: '左上角Y坐标', code: 'LeftTopY' },
    { label: '右上角X坐标', code: 'RightBtmX' },
    { label: '右上角Y坐标', code: 'RightBtmy' },
    { label: '位置标记时间', code: 'MarkTime', type: 'time' },
    { label: '车辆出现时间', code: 'AppearTime', type: 'time' },
    { label: '车辆消失时间', code: 'DisappearTime', type: 'time' },
    { label: '车道号', code: 'LaneNo' },
    { label: '有无车牌', code: 'HasPlate' },
    { label: '号牌种类', code: 'PlateClass' },
    { label: '车牌颜色', code: 'PlateColor' },
    { label: '车牌号', code: 'PlateNo' },
    { label: '挂车牌号', code: 'PlateNoAttach' },
    { label: '车牌描述', code: 'PlateDescribe' },
    { label: '是否套牌', code: 'IsDecked' },
    { label: '是否涂改', code: 'IsAltered' },
    { label: '是否遮挡', code: 'IsCovered' },
    { label: '行驶速度(km/h)', code: 'Speed' },
    { label: '行驶方向', code: 'Direction' },
    { label: '行驶状态', code: 'DrivingStatusCode' },
    { label: '车辆使用性质代码', code: 'UsingPropertiesCode' },
    { label: '车辆类型', code: 'VehicleClass' },
    { label: '车辆品牌', code: 'VehicleBrand' },
    { label: '车辆型号', code: 'VehicleModel' },
    { label: '车辆年款', code: 'VehicleStyles' },
    { label: '车辆长度', code: 'VehicleLength' },
    { label: '车辆宽度', code: 'VehicleWidth' },
    { label: '车辆高度', code: 'VehicleHeight' },
    { label: '车身颜色', code: 'VehicleColor' },
    { label: '颜色深浅', code: 'VehicleColorDepth' },
    { label: '车前盖', code: 'VehicleHood' },
    { label: '车轮', code: 'VehicleWheel' },
    { label: '车后盖', code: 'VehicleTrunk' },
    { label: '车轮印花纹', code: 'WheelPrintedPattern' },
    { label: '车窗', code: 'VehicleWindow' },
    { label: '车顶', code: 'VehicleRoof' },
    { label: '车门', code: 'VehicleDoor' },
    { label: '车侧', code: 'SideOfVehicle' },
    { label: '车厢', code: 'CarOfVehicle' },
    { label: '后视镜', code: 'RearviewMirror' },
    { label: '底盘', code: 'VehicleChassis' },
    { label: '遮挡', code: 'VehicleShielding' },
    { label: '贴膜颜色', code: 'FilmColor' },
    { label: '改装标志', code: 'IsModified' },
    { label: '车窗', code: 'VehicleWindow' },
    { label: '撞痕信息', code: 'HitMarkInfo' },
    { label: '车身描述', code: 'VehicleBodyDesc' },
    { label: '车前部物品', code: 'VehicleFrontItem' },
    { label: '车前部物品描述', code: 'DescOfFrontItem' },
    { label: '车后部物品', code: 'VehicleRearItem' },
    { label: '车后部物品描述', code: 'DescOfRearItem' },
    { label: '车内人数', code: 'NumOfPassenger' },
    { label: '经过时刻', code: 'PassTime', type: 'time' },
    { label: '经过道路名称', code: 'NameOfPassedRoad' },
    { label: '是否可疑车', code: 'IsSuspicious', format: { 0: '否', 1: '是' } },
    { label: '遮阳板状态', code: 'Sunvisor', format: { 0: '收起', 1: '放下' } },
    { label: '安全带状态', code: 'SafetyBelt', format: { 0: '未系', 1: '有系' } },
    { label: '打电话状态', code: 'Calling', format: { 0: '未打电话', 1: '打电话中' } },
    { label: '号牌识别可信度', code: 'PlateReliability' },
    { label: '每位号牌号码可信度', code: 'PlateCharReliability' },
    { label: '品牌标志识别可信度', code: 'BrandReliability' },    
  ],
  // 非机动车
  'NonMotorVehicle': [
    { label: '车辆标识', code: 'NonMotorVehicleID' },
    { label: '信息分类', code: 'InfoType' },
    { label: '来源标识', code: 'SourceID' },
    { label: '位置标记时间', code: 'MarkTime', type: 'time' },
    { label: '左上角X坐标', code: 'LeftTopX' },
    { label: '左上角Y坐标', code: 'LeftTopY' },
    { label: '右上角X坐标', code: 'RightBtmX' },
    { label: '右上角Y坐标', code: 'RightBtmy' },
    { label: '车辆出现时间', code: 'AppearTime', type: 'time' },
    { label: '车辆消失时间', code: 'DisappearTime', type: 'time' },
    { label: '号牌种类', code: 'PlateClass' },
    { label: '车牌颜色', code: 'PlateColor' },
    { label: '车牌号', code: 'PlateNo' },
    { label: '挂车牌号', code: 'PlateNoAttach' },
    { label: '车牌描述', code: 'PlateDescribe' },
    { label: '是否套牌', code: 'IsDecked' },
    { label: '是否涂改', code: 'IsAltered' },
    { label: '是否遮挡', code: 'IsCovered' },
    { label: '行驶速度(km/h)', code: 'Speed' },
    { label: '行驶状态', code: 'DrivingStatusCode' },
    { label: '车辆使用性质代码', code: 'UsingPropertiesCode' },
    { label: '车辆款型', code: 'VehicleType' },
    { label: '车辆长度', code: 'VehicleLength' },
    { label: '车辆宽度', code: 'VehicleWidth' },
    { label: '车辆高度', code: 'VehicleHeight' },
    { label: '车身颜色', code: 'VehicleColor' },
    { label: '车前盖', code: 'VehicleHood' },
    { label: '车轮', code: 'VehicleWheel' },
    { label: '车后盖', code: 'VehicleTrunk' },
    { label: '车轮印花纹', code: 'WheelPrintedPattern' },
    { label: '车窗', code: 'VehicleWindow' },
    { label: '车顶', code: 'VehicleRoof' },
    { label: '车门', code: 'VehicleDoor' },
    { label: '车侧', code: 'SideOfVehicle' },
    { label: '车厢', code: 'CarOfVehicle' },
    { label: '后视镜', code: 'RearviewMirror' },
    { label: '底盘', code: 'VehicleChassis' },
    { label: '遮挡', code: 'VehicleShielding' },
    { label: '贴膜颜色', code: 'FilmColor' },
    { label: '改装标志', code: 'IsModified' },
  ]
}